//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcStaffDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string snumber { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string full_name { get; set; }
        public string room { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<bool> show { get; set; }
        public string school_code { get; set; }
        public string school_name { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
        public string instr_code { get; set; }
        public string instr_title { get; set; }
        public string mgr_id { get; set; }
    }
}
