//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcStaffDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcorpdir
    {
        public string EMPLOYEEID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string DISPLAYNAME { get; set; }
        public string OFFICE { get; set; }
        public string PHONE { get; set; }
        public string MAIL { get; set; }
        public string DIRECTORY { get; set; }
        public string DIVISIONID { get; set; }
        public string DIVISION { get; set; }
        public string DEPTMENTID { get; set; }
        public string DEPTMENT { get; set; }
        public string POSITIONID { get; set; }
        public string POSITION { get; set; }
        public string MANAGER { get; set; }
    }
}
